---
- name: Install Qdrant on DB server
  hosts: all
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
          - unzip
        state: present
        update_cache: yes

    - name: Download Qdrant binary
      get_url:
        url: https://github.com/qdrant/qdrant/releases/download/v1.12.4/qdrant-v1.12.4-x86_64-unknown-linux-gnu.zip
        dest: /tmp/qdrant.zip

    - name: Unpack Qdrant binary
      unarchive:
        src: /tmp/qdrant.zip
        dest: /opt/
        remote_src: yes

    - name: Create config directory
      file:
        path: /etc/qdrant
        state: directory

    - name: Copy Qdrant config
      copy:
        src: ../config/qdrant.yaml
        dest: /etc/qdrant/qdrant.yaml

    - name: Install systemd service file
      copy:
        src: ../deploy/qdrant.service
        dest: /etc/systemd/system/qdrant.service
        mode: '0644'

    - name: Enable and start Qdrant
      systemd:
        name: qdrant
        enabled: yes
        state: started